### ISSUE TITLE
UK postcodes should be on a separate line

### ISSUE THREAD

**Issue by DrHyde** [OpenCageData/perl-Geo-Address-Formatter#7]
`worldwide.yaml` say that a UK postcode goes immediately after the post town and on the same line. It should be on its own on the following line. ie ...

Incorrect:
```
12 Letsby Avenue
Sheffield S9 1XX
```
Correct:
```
12 Letsby Avenue
Sheffield
S9 1XX
```

**Comment by freyfogle** [comment]
hmm, yes, though surely both ways are in common usage

**Comment by freyfogle** [comment]
hmm, I just checked 10 UK websites, see it half one way, half the other. That said, the Royal Mail does seem to advise postcode on its own line.

Anyway,  this issue is more correctly filed in [address-formatting](https://github.com/OpenCageData/address-formatting) which is where the templates live. The idea being that the templates are independent of any individual programming language.

Geo::Address::Formatter "just" processes the templates in Perl.
